CREATE TABLE Item(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  description VARCHAR(80) NOT NULL,
  price BIGINT NOT NULL,
  userId BIGINT
);

CREATE TABLE Siteuser(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR(80),
  lastName VARCHAR(80),
  email VARCHAR(80),
  password VARCHAR(80)
);

ALTER TABLE Item ADD FOREIGN KEY (userId) REFERENCES Siteuser(id);
